ParameterSliderFilterOption:
    type: object
    inherits:
        - 'AppParameterFilterOptionDecorator'
    config:
        fields:
            minimalValue:
                type: "Float!"
                description: "The parameter minimal value"
            maximalValue:
                type: "Float!"
                description: "The parameter maximal value"
            selectedValue:
                type: "Float"
                description: "The pre-selected value (used for \"ready category seo mixes\")"
            isSelectable:
                type: "Boolean!"
                description: "Can be used in filter"
