doctrine_migrations:
    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/src/Migrations'
    storage:
        table_storage:
            table_name: migrations
    services:
        'Doctrine\Migrations\Version\Comparator': 'Shopsys\MigrationBundle\Component\Doctrine\Migrations\MigrationsLockComparator'
        'Doctrine\Migrations\Version\MigrationPlanCalculator': 'Shopsys\MigrationBundle\Component\Doctrine\Migrations\MigrationLockPlanCalculator'
        'Doctrine\Migrations\MigrationsRepository': 'Shopsys\MigrationBundle\Component\Doctrine\Migrations\MigrationsLockRepository'
        'Doctrine\Migrations\Version\Executor': 'Shopsys\MigrationBundle\Component\Doctrine\Migrations\MigrationsExecutor'
