framework:
    annotations:
        cache: file
        file_cache_dir: '%kernel.cache_dir%/annotations'
    secret: "%env(APP_SECRET)%"
    router:
        utf8: true
        strict_requirements: true
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    trusted_hosts: ~
    session:
        handler_id: snc_redis.session.handler
        cookie_httponly: true
        # Disable the default PHP session garbage collection.
        # Session garbage collection is responsibility of hosting.
        gc_probability: 0
    fragments: ~
    http_method_override: true
    profiler:
        enabled: false
        collect: false
    assets: ~
    error_controller: 'Shopsys\FrameworkBundle\Component\Error\ErrorController::showAction'
