
front_brand_list:
    path: /brands-overview

front_customer_activation:
    path: /registration-confirmation
front_customer_order_detail_registered:
    path: /customer/orders/detail/{orderNumber}

front_customer_order_detail_unregistered:
    path: /order-detail/{urlHash}

front_login:
    path: /login/

front_logout:
    # controller's action is unnecessary, because firewall processes whole request
    path: /logout/{_csrf_token}

front_order_paid:
    path: /order-payment-confirmation

front_order_payment_status_notify:
    methods: [GET]
    path: /order/payment-status-notify

front_personal_data:
    path: /personal-data-overview

front_personal_data_access:
    path: /personal-data-overview/{hash}

front_personal_data_export:
    path: /personal-data-export

front_registration_set_new_password:
    path: /new-password

front_stores:
    path: /stores
