parameters:
    internal_directories:
        - '%kernel.cache_dir%/localeFileUploads'
        - '%kernel.project_dir%/var/overblogCompiledClasses'
    public_directories:
        - "%shopsys.product_files_dir%"
