Wishlist:
    type: object
    config:
        fields:
            uuid:
                type: "Uuid!"
                description: "Wishlist identifier"
            products:
                type: "[Product!]!"
                description: "List of wishlist products"
                resolve: '@=query("productsByWishlistQuery", value)'
