WishlistQuery:
    type: object
    config:
        fields:
            wishlist:
                type: "Wishlist"
                resolve: "@=query('wishlistQuery', args['wishlistUuid'])"
                args:
                    wishlistUuid:
                        type: "Uuid"
                description: "Get wishlist by uuid or if customer is logged, try find for logged customer."
