bases:
    - ../../base
resources:
    - ../../../deployments/adminer.yml
    - ../../../deployments/redis-admin.yml
    - ../../../deployments/selenium-server.yml
    - ../../../services/adminer.yml
    - ../../../services/redis-admin.yml
    - ../../../services/selenium-server.yml
patchesJson6902:
    -   target:
            group: extensions
            version: v1beta1
            kind: Ingress
            name: shopsys
        path: ./ingress-patch.yaml
    -   target:
            group: apps
            version: v1
            kind: Deployment
            name: webserver-php-fpm
        path: ./webserver-php-fpm-patch.yaml
configMapGenerator:
    -   name: nginx-configuration
        files:
            - ../../../../../docker/nginx/nginx.conf
