
front_download_uploaded_file:
    defaults: { _controller: App\Controller\Front\UploadedFileController::downloadAction }
    methods: [GET]
    path: /file/{uploadedFileId}/{uploadedFilename}
    requirements:
        uploadedFileId: \d+

front_export_personal_data:
    defaults:
        _controller: App\Controller\Front\PersonalDataController::exportXmlAction
        type: ~
    path: /personal-overview-export/xml/{hash}
front_homepage:
    path: /
