sentry:
    dsn: '%env(SENTRY_DSN)%'
    messenger:
        capture_soft_fails: true # captures exceptions marked for retry too
        enabled: true # flushes Sentry messages at the end of each message handling
    options:
        environment: '%env(SENTRY_ENVIRONMENT)%'
        release: '%env(SENTRY_RELEASE)%'
    register_error_listener: false

services:
    Sentry\Monolog\Handler:
        arguments:
            $hub: '@Sentry\State\HubInterface'
            $level: !php/const Monolog\Logger::ERROR
            $bubble: true
            $fillExtraContext: true
