ProductConnection:
    type: relay-connection
    config:
        nodeType: Product
        connectionFields:
            totalCount:
                type: "Int!"
                description: "Total number of products"
            productFilterOptions:
                type: "ProductFilterOptions!"
    inherits:
        - 'ProductConnectionDecorator'
