overblog_graphql:
    definitions:
        auto_compile: true
        builders:
            args:
                -   alias: "ProductPaginatorArgumentsBuilder"
                    class: Shopsys\FrontendApiBundle\Component\Arguments\ProductPaginatorArgumentsBuilder
                -   alias: "ProductSearchPaginatorArgumentsBuilder"
                    class: Shopsys\FrontendApiBundle\Component\Arguments\ProductSearchPaginatorArgumentsBuilder
                -   alias: "BlogArticlePaginatorArgumentsBuilder"
                    class: Shopsys\FrontendApiBundle\Component\Arguments\BlogArticlePaginatorArgumentsBuilder
        cache_dir: '%kernel.project_dir%/var/overblogCompiledClasses'
        mappings:
            types:
                -   type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
        schema:
            query: Query
            mutation: Mutation
        # these settings are suggested by docs: https://github.com/overblog/GraphQLBundle/blob/master/docs/index.md#composer-autoloader-configuration-optional
        use_classloader_listener: false
    errors_handler:
        logger_service: Shopsys\FrontendApiBundle\Model\Logger\FrontendApiLogger
    security:
        enable_introspection: '%kernel.debug%'
        handle_cors: true
        query_max_complexity: 1110
    services:
        promise_adapter: "webonyx_graphql.sync_promise_adapter"
