parameters:
    packetery_config:
        api_password: '%env(PACKETERY_API_PASSWORD)%'
        enabled: '%env(bool:PACKETERY_ENABLED)%'
        rest_api_url: '%env(PACKETERY_REST_API_URL)%'
        sender: '%env(PACKETERY_SENDER)%'
