parameters:
    shopsys.router.friendly_url_router_filepath: '%kernel.project_dir%/config/shopsys-routing/routing_friendly_url.yaml'
    shopsys.router.locale_router_filepath_mask: '%kernel.project_dir%/config/shopsys-routing/routing_front_*.yaml'
