snc_redis:
    clients:
        bestselling_products:
            type: 'phpredis'
            alias: 'bestselling_products'
            dsn: 'redis://%env(REDIS_HOST)%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%:cache:bestselling_products:'
        doctrine_query:
            type: 'phpredis'
            alias: 'doctrine_query'
            dsn: 'redis://%env(REDIS_HOST)%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%:cache:doctrine:query:'
        # client is used exclusively for cleaning old versions of redis caches and should not be used for anything else
        global:
            type: 'phpredis'
            alias: 'global'
            dsn: 'redis://%env(REDIS_HOST)%'
            options:
                prefix: '%env(REDIS_PREFIX)%'
        main_friendly_url_slugs:
            type: 'phpredis'
            alias: 'main_friendly_url_slugs'
            dsn: 'redis://%env(REDIS_HOST)%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%:cache:main_friendly_url_slugs:'
