apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: redis-admin
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: redis-admin
        spec:
            containers:
                -   name: redis-commander
                    image: ghcr.io/joeferner/redis-commander:latest
                    env:
                        -   name: REDIS_HOST
                            value: redis
                    ports:
                        -   name: http
                            containerPort: 8081
                            protocol: TCP
